const GET_CLOCKS = 'GET_ClOCKS';
const ADD_CLOCK = 'ADD_CLOCK';
const DELETE_CLOCK = 'DELETE_CLOCK';
const CHANGE_TIMEZONE = 'CHANGE_TIMEZONE';

export { GET_CLOCKS, ADD_CLOCK, DELETE_CLOCK, CHANGE_TIMEZONE };
